#!/bin/bash
# Build libjavasmtstp.so - run from this directory
# Generated by ChatGPT to automatically build the library for the JNI wrapper
set -e
cd "$(dirname "$0")"

JNI_INCLUDES="-I${JAVA_HOME:-$(dirname $(dirname $(readlink -f $(which java))))}/include -I${JAVA_HOME:-$(dirname $(dirname $(readlink -f $(which java))))}/include/linux"

gcc -fPIC -shared -Wall -I. $JNI_INCLUDES -c stp_wrap.c -o stp_wrap.o
gcc -shared -o libjavasmtstp.so stp_wrap.o -L. -lstp -labc-pic -l:libminisat.so.2 -Wl,-rpath,'$ORIGIN'

echo "Built libjavasmtstp.so"