/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


#define SWIG_VERSION 0x040200
#define SWIGJAVA

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif

#if __cplusplus >=201103L
# define SWIG_NULLPTR nullptr
#else
# define SWIG_NULLPTR NULL
#endif 


#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1,
  SWIG_JavaIOException,
  SWIG_JavaRuntimeException,
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError,
  SWIG_JavaIllegalStateException,
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { SWIG_JavaIllegalStateException, "java/lang/IllegalStateException" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) do { if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } } while (0)


#include "c_interface.h"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jstring JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_get_1git_1version_1sha(JNIEnv *jenv, jclass jcls) {
  jstring jresult = 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (char *)get_git_version_sha();
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_get_1git_1version_1tag(JNIEnv *jenv, jclass jcls) {
  jstring jresult = 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (char *)get_git_version_tag();
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_get_1compilation_1env(JNIEnv *jenv, jclass jcls) {
  jstring jresult = 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (char *)get_compilation_env();
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_process_1argument(JNIEnv *jenv, jclass jcls, jchar jarg1, jlong jarg2) {
  char arg1 ;
  VC arg2 = (VC) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (char)jarg1; 
  arg2 = *(VC *)&jarg2; 
  process_argument(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1setFlags(JNIEnv *jenv, jclass jcls, jlong jarg1, jchar jarg2, jint jarg3) {
  VC arg1 = (VC) 0 ;
  char arg2 ;
  int arg3 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = (char)jarg2; 
  arg3 = (int)jarg3; 
  vc_setFlags(arg1,arg2,arg3);
}


SWIGEXPORT void JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1setFlag(JNIEnv *jenv, jclass jcls, jlong jarg1, jchar jarg2) {
  VC arg1 = (VC) 0 ;
  char arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = (char)jarg2; 
  vc_setFlag(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1setInterfaceFlags(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3) {
  VC arg1 = (VC) 0 ;
  enum ifaceflag_t arg2 ;
  int arg3 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = (enum ifaceflag_t)jarg2; 
  arg3 = (int)jarg3; 
  vc_setInterfaceFlags(arg1,arg2,arg3);
}


SWIGEXPORT void JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_make_1division_1total(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  VC arg1 = (VC) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  make_division_total(arg1);
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1createValidityChecker(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  VC result;
  
  (void)jenv;
  (void)jcls;
  result = (VC)vc_createValidityChecker();
  *(VC *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1boolType(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Type result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  result = (Type)vc_boolType(arg1);
  *(Type *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1arrayType(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Type arg2 = (Type) 0 ;
  Type arg3 = (Type) 0 ;
  Type result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Type *)&jarg2; 
  arg3 = *(Type *)&jarg3; 
  result = (Type)vc_arrayType(arg1,arg2,arg3);
  *(Type *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1varExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  char *arg2 = (char *) 0 ;
  Type arg3 = (Type) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = *(Type *)&jarg3; 
  result = (Expr)vc_varExpr(arg1,(char const *)arg2,arg3);
  *(Expr *)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1varExpr1(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jint jarg3, jint jarg4) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  int arg4 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  result = (Expr)vc_varExpr1(arg1,(char const *)arg2,arg3,arg4);
  *(Expr *)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1getType(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  Type result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  result = (Type)vc_getType(arg1,arg2);
  *(Type *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1getBVLength(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  result = (int)vc_getBVLength(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1eqExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  Expr arg3 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  arg3 = *(Expr *)&jarg3; 
  result = (Expr)vc_eqExpr(arg1,arg2,arg3);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1trueExpr(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  result = (Expr)vc_trueExpr(arg1);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1falseExpr(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  result = (Expr)vc_falseExpr(arg1);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1notExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  result = (Expr)vc_notExpr(arg1,arg2);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1andExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  Expr arg3 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  arg3 = *(Expr *)&jarg3; 
  result = (Expr)vc_andExpr(arg1,arg2,arg3);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1orExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  Expr arg3 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  arg3 = *(Expr *)&jarg3; 
  result = (Expr)vc_orExpr(arg1,arg2,arg3);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1xorExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  Expr arg3 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  arg3 = *(Expr *)&jarg3; 
  result = (Expr)vc_xorExpr(arg1,arg2,arg3);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1impliesExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  Expr arg3 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  arg3 = *(Expr *)&jarg3; 
  result = (Expr)vc_impliesExpr(arg1,arg2,arg3);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1iffExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  Expr arg3 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  arg3 = *(Expr *)&jarg3; 
  result = (Expr)vc_iffExpr(arg1,arg2,arg3);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1iteExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  Expr arg3 = (Expr) 0 ;
  Expr arg4 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  arg3 = *(Expr *)&jarg3; 
  arg4 = *(Expr *)&jarg4; 
  result = (Expr)vc_iteExpr(arg1,arg2,arg3,arg4);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1boolToBVExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  result = (Expr)vc_boolToBVExpr(arg1,arg2);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1paramBoolExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  Expr arg3 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  arg3 = *(Expr *)&jarg3; 
  result = (Expr)vc_paramBoolExpr(arg1,arg2,arg3);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1readExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  Expr arg3 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  arg3 = *(Expr *)&jarg3; 
  result = (Expr)vc_readExpr(arg1,arg2,arg3);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1writeExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  Expr arg3 = (Expr) 0 ;
  Expr arg4 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  arg3 = *(Expr *)&jarg3; 
  arg4 = *(Expr *)&jarg4; 
  result = (Expr)vc_writeExpr(arg1,arg2,arg3,arg4);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1parseExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  char *arg2 = (char *) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (Expr)vc_parseExpr(arg1,(char const *)arg2);
  *(Expr *)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1printExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  vc_printExpr(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1printExprCCode(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  vc_printExprCCode(arg1,arg2);
}


SWIGEXPORT jstring JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1printSMTLIB(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jstring jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  result = (char *)vc_printSMTLIB(arg1,arg2);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1printExprFile(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3) {
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  int arg3 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  arg3 = (int)jarg3; 
  vc_printExprFile(arg1,arg2,arg3);
}


SWIGEXPORT void JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1printCounterExample(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  VC arg1 = (VC) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  vc_printCounterExample(arg1);
}


SWIGEXPORT void JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1printVarDecls(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  VC arg1 = (VC) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  vc_printVarDecls(arg1);
}


SWIGEXPORT void JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1clearDecls(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  VC arg1 = (VC) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  vc_clearDecls(arg1);
}


SWIGEXPORT void JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1printAsserts(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  VC arg1 = (VC) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = (int)jarg2; 
  vc_printAsserts(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1printQuery(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  VC arg1 = (VC) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  vc_printQuery(arg1);
}


SWIGEXPORT void JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1assertFormula(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  vc_assertFormula(arg1,arg2);
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1simplify(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  result = (Expr)vc_simplify(arg1,arg2);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1query_1with_1timeout(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jint jarg4) {
  jint jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  int arg3 ;
  int arg4 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  result = (int)vc_query_with_timeout(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1query(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  result = (int)vc_query(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1getCounterExample(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  result = (Expr)vc_getCounterExample(arg1,arg2);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1counterexample_1size(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  VC arg1 = (VC) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  result = (int)vc_counterexample_size(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1push(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  VC arg1 = (VC) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  vc_push(arg1);
}


SWIGEXPORT void JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1pop(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  VC arg1 = (VC) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  vc_pop(arg1);
}


SWIGEXPORT jint JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_getBVInt(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  Expr arg1 = (Expr) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Expr *)&jarg1; 
  result = (int)getBVInt(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_getBVUnsigned(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  Expr arg1 = (Expr) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Expr *)&jarg1; 
  result = (unsigned int)getBVUnsigned(arg1);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jobject JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_getBVUnsignedLongLong(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jobject jresult = 0 ;
  Expr arg1 = (Expr) 0 ;
  unsigned long long result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Expr *)&jarg1; 
  result = (unsigned long long)getBVUnsignedLongLong(arg1);
  {
    jbyteArray ba = (*jenv)->NewByteArray(jenv, 9);
    jbyte* bae = (*jenv)->GetByteArrayElements(jenv, ba, 0);
    jclass clazz = (*jenv)->FindClass(jenv, "java/math/BigInteger");
    jmethodID mid = (*jenv)->GetMethodID(jenv, clazz, "<init>", "([B)V");
    jobject bigint;
    int i;
    
    bae[0] = 0;
    for(i=1; i<9; i++ ) {
      bae[i] = (jbyte)(result>>8*(8-i));
    }
    
    (*jenv)->ReleaseByteArrayElements(jenv, ba, bae, 0);
    bigint = (*jenv)->NewObject(jenv, clazz, mid, ba);
    (*jenv)->DeleteLocalRef(jenv, ba);
    jresult = bigint;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bvType(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  int arg2 ;
  Type result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = (int)jarg2; 
  result = (Type)vc_bvType(arg1,arg2);
  *(Type *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bv32Type(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Type result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  result = (Type)vc_bv32Type(arg1);
  *(Type *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1getValueSize(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Type arg2 = (Type) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Type *)&jarg2; 
  result = (int)vc_getValueSize(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1getIndexSize(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Type arg2 = (Type) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Type *)&jarg2; 
  result = (int)vc_getIndexSize(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bvConstExprFromDecStr(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jstring jarg3) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  int arg2 ;
  char *arg3 = (char *) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  result = (Expr)vc_bvConstExprFromDecStr(arg1,arg2,(char const *)arg3);
  *(Expr *)&jresult = result; 
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bvConstExprFromStr(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  char *arg2 = (char *) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (Expr)vc_bvConstExprFromStr(arg1,(char const *)arg2);
  *(Expr *)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bvConstExprFromInt(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  int arg2 ;
  unsigned int arg3 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (unsigned int)jarg3; 
  result = (Expr)vc_bvConstExprFromInt(arg1,arg2,arg3);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bvConstExprFromLL(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jobject jarg3) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  int arg2 ;
  unsigned long long arg3 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = (int)jarg2; 
  {
    jclass clazz;
    jmethodID mid;
    jbyteArray ba;
    jbyte* bae;
    jsize sz;
    int i;
    
    if (!jarg3) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "BigInteger null");
      return 0;
    }
    clazz = (*jenv)->GetObjectClass(jenv, jarg3);
    mid = (*jenv)->GetMethodID(jenv, clazz, "toByteArray", "()[B");
    ba = (jbyteArray)(*jenv)->CallObjectMethod(jenv, jarg3, mid);
    bae = (*jenv)->GetByteArrayElements(jenv, ba, 0);
    sz = (*jenv)->GetArrayLength(jenv, ba);
    arg3 = 0;
    if (sz > 0) {
      arg3 = (unsigned long long)(signed char)bae[0];
      for(i=1; i<sz; i++) {
        arg3 = (arg3 << 8) | (unsigned long long)(unsigned char)bae[i];
      }
    }
    (*jenv)->ReleaseByteArrayElements(jenv, ba, bae, 0);
  }
  result = (Expr)vc_bvConstExprFromLL(arg1,arg2,arg3);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bv32ConstExprFromInt(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  unsigned int arg2 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  result = (Expr)vc_bv32ConstExprFromInt(arg1,arg2);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bvConcatExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  Expr arg3 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  arg3 = *(Expr *)&jarg3; 
  result = (Expr)vc_bvConcatExpr(arg1,arg2,arg3);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bvPlusExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  int arg2 ;
  Expr arg3 = (Expr) 0 ;
  Expr arg4 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = *(Expr *)&jarg3; 
  arg4 = *(Expr *)&jarg4; 
  result = (Expr)vc_bvPlusExpr(arg1,arg2,arg3,arg4);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bv32PlusExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  Expr arg3 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  arg3 = *(Expr *)&jarg3; 
  result = (Expr)vc_bv32PlusExpr(arg1,arg2,arg3);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bvMinusExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  int arg2 ;
  Expr arg3 = (Expr) 0 ;
  Expr arg4 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = *(Expr *)&jarg3; 
  arg4 = *(Expr *)&jarg4; 
  result = (Expr)vc_bvMinusExpr(arg1,arg2,arg3,arg4);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bv32MinusExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  Expr arg3 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  arg3 = *(Expr *)&jarg3; 
  result = (Expr)vc_bv32MinusExpr(arg1,arg2,arg3);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bvMultExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  int arg2 ;
  Expr arg3 = (Expr) 0 ;
  Expr arg4 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = *(Expr *)&jarg3; 
  arg4 = *(Expr *)&jarg4; 
  result = (Expr)vc_bvMultExpr(arg1,arg2,arg3,arg4);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bv32MultExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  Expr arg3 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  arg3 = *(Expr *)&jarg3; 
  result = (Expr)vc_bv32MultExpr(arg1,arg2,arg3);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bvDivExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  int arg2 ;
  Expr arg3 = (Expr) 0 ;
  Expr arg4 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = *(Expr *)&jarg3; 
  arg4 = *(Expr *)&jarg4; 
  result = (Expr)vc_bvDivExpr(arg1,arg2,arg3,arg4);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bvModExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  int arg2 ;
  Expr arg3 = (Expr) 0 ;
  Expr arg4 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = *(Expr *)&jarg3; 
  arg4 = *(Expr *)&jarg4; 
  result = (Expr)vc_bvModExpr(arg1,arg2,arg3,arg4);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bvRemExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  int arg2 ;
  Expr arg3 = (Expr) 0 ;
  Expr arg4 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = *(Expr *)&jarg3; 
  arg4 = *(Expr *)&jarg4; 
  result = (Expr)vc_bvRemExpr(arg1,arg2,arg3,arg4);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1sbvDivExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  int arg2 ;
  Expr arg3 = (Expr) 0 ;
  Expr arg4 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = *(Expr *)&jarg3; 
  arg4 = *(Expr *)&jarg4; 
  result = (Expr)vc_sbvDivExpr(arg1,arg2,arg3,arg4);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1sbvModExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  int arg2 ;
  Expr arg3 = (Expr) 0 ;
  Expr arg4 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = *(Expr *)&jarg3; 
  arg4 = *(Expr *)&jarg4; 
  result = (Expr)vc_sbvModExpr(arg1,arg2,arg3,arg4);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1sbvRemExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  int arg2 ;
  Expr arg3 = (Expr) 0 ;
  Expr arg4 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = *(Expr *)&jarg3; 
  arg4 = *(Expr *)&jarg4; 
  result = (Expr)vc_sbvRemExpr(arg1,arg2,arg3,arg4);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bvLtExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  Expr arg3 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  arg3 = *(Expr *)&jarg3; 
  result = (Expr)vc_bvLtExpr(arg1,arg2,arg3);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bvLeExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  Expr arg3 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  arg3 = *(Expr *)&jarg3; 
  result = (Expr)vc_bvLeExpr(arg1,arg2,arg3);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bvGtExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  Expr arg3 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  arg3 = *(Expr *)&jarg3; 
  result = (Expr)vc_bvGtExpr(arg1,arg2,arg3);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bvGeExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  Expr arg3 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  arg3 = *(Expr *)&jarg3; 
  result = (Expr)vc_bvGeExpr(arg1,arg2,arg3);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1sbvLtExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  Expr arg3 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  arg3 = *(Expr *)&jarg3; 
  result = (Expr)vc_sbvLtExpr(arg1,arg2,arg3);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1sbvLeExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  Expr arg3 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  arg3 = *(Expr *)&jarg3; 
  result = (Expr)vc_sbvLeExpr(arg1,arg2,arg3);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1sbvGtExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  Expr arg3 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  arg3 = *(Expr *)&jarg3; 
  result = (Expr)vc_sbvGtExpr(arg1,arg2,arg3);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1sbvGeExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  Expr arg3 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  arg3 = *(Expr *)&jarg3; 
  result = (Expr)vc_sbvGeExpr(arg1,arg2,arg3);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bvUMinusExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  result = (Expr)vc_bvUMinusExpr(arg1,arg2);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bvAndExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  Expr arg3 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  arg3 = *(Expr *)&jarg3; 
  result = (Expr)vc_bvAndExpr(arg1,arg2,arg3);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bvOrExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  Expr arg3 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  arg3 = *(Expr *)&jarg3; 
  result = (Expr)vc_bvOrExpr(arg1,arg2,arg3);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bvXorExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  Expr arg3 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  arg3 = *(Expr *)&jarg3; 
  result = (Expr)vc_bvXorExpr(arg1,arg2,arg3);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bvNotExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  result = (Expr)vc_bvNotExpr(arg1,arg2);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bvLeftShiftExprExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  int arg2 ;
  Expr arg3 = (Expr) 0 ;
  Expr arg4 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = *(Expr *)&jarg3; 
  arg4 = *(Expr *)&jarg4; 
  result = (Expr)vc_bvLeftShiftExprExpr(arg1,arg2,arg3,arg4);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bvRightShiftExprExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  int arg2 ;
  Expr arg3 = (Expr) 0 ;
  Expr arg4 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = *(Expr *)&jarg3; 
  arg4 = *(Expr *)&jarg4; 
  result = (Expr)vc_bvRightShiftExprExpr(arg1,arg2,arg3,arg4);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bvSignedRightShiftExprExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jlong jarg4) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  int arg2 ;
  Expr arg3 = (Expr) 0 ;
  Expr arg4 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = *(Expr *)&jarg3; 
  arg4 = *(Expr *)&jarg4; 
  result = (Expr)vc_bvSignedRightShiftExprExpr(arg1,arg2,arg3,arg4);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bvLeftShiftExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  int arg2 ;
  Expr arg3 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = *(Expr *)&jarg3; 
  result = (Expr)vc_bvLeftShiftExpr(arg1,arg2,arg3);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bvRightShiftExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  int arg2 ;
  Expr arg3 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = *(Expr *)&jarg3; 
  result = (Expr)vc_bvRightShiftExpr(arg1,arg2,arg3);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bv32LeftShiftExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  int arg2 ;
  Expr arg3 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = *(Expr *)&jarg3; 
  result = (Expr)vc_bv32LeftShiftExpr(arg1,arg2,arg3);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bv32RightShiftExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  int arg2 ;
  Expr arg3 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = *(Expr *)&jarg3; 
  result = (Expr)vc_bv32RightShiftExpr(arg1,arg2,arg3);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bvVar32LeftShiftExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  Expr arg3 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  arg3 = *(Expr *)&jarg3; 
  result = (Expr)vc_bvVar32LeftShiftExpr(arg1,arg2,arg3);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bvVar32RightShiftExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  Expr arg3 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  arg3 = *(Expr *)&jarg3; 
  result = (Expr)vc_bvVar32RightShiftExpr(arg1,arg2,arg3);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bvVar32DivByPowOfTwoExpr(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  Expr arg3 = (Expr) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  arg3 = *(Expr *)&jarg3; 
  result = (Expr)vc_bvVar32DivByPowOfTwoExpr(arg1,arg2,arg3);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bvExtract(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jint jarg4) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  int arg3 ;
  int arg4 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  result = (Expr)vc_bvExtract(arg1,arg2,arg3,arg4);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bvBoolExtract(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  int arg3 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  arg3 = (int)jarg3; 
  result = (Expr)vc_bvBoolExtract(arg1,arg2,arg3);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bvBoolExtract_1Zero(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  int arg3 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  arg3 = (int)jarg3; 
  result = (Expr)vc_bvBoolExtract_Zero(arg1,arg2,arg3);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bvBoolExtract_1One(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  int arg3 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  arg3 = (int)jarg3; 
  result = (Expr)vc_bvBoolExtract_One(arg1,arg2,arg3);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bvSignExtend(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  int arg3 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  arg3 = (int)jarg3; 
  result = (Expr)vc_bvSignExtend(arg1,arg2,arg3);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bvCreateMemoryArray(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  char *arg2 = (char *) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (Expr)vc_bvCreateMemoryArray(arg1,(char const *)arg2);
  *(Expr *)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bvReadMemoryArray(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jint jarg4) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  Expr arg3 = (Expr) 0 ;
  int arg4 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  arg3 = *(Expr *)&jarg3; 
  arg4 = (int)jarg4; 
  result = (Expr)vc_bvReadMemoryArray(arg1,arg2,arg3,arg4);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1bvWriteToMemoryArray(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jint jarg5) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  Expr arg3 = (Expr) 0 ;
  Expr arg4 = (Expr) 0 ;
  int arg5 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  arg3 = *(Expr *)&jarg3; 
  arg4 = *(Expr *)&jarg4; 
  arg5 = (int)jarg5; 
  result = (Expr)vc_bvWriteToMemoryArray(arg1,arg2,arg3,arg4,arg5);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_exprString(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jstring jresult = 0 ;
  Expr arg1 = (Expr) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Expr *)&jarg1; 
  result = (char *)exprString(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_typeString(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jstring jresult = 0 ;
  Type arg1 = (Type) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Type *)&jarg1; 
  result = (char *)typeString(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_getChild(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jlong jresult = 0 ;
  Expr arg1 = (Expr) 0 ;
  int arg2 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Expr *)&jarg1; 
  arg2 = (int)jarg2; 
  result = (Expr)getChild(arg1,arg2);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1isBool(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  Expr arg1 = (Expr) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Expr *)&jarg1; 
  result = (int)vc_isBool(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1registerErrorHandler(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  void (*arg1)(char const *) = (void (*)(char const *)) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void (**)(char const *))&jarg1; 
  vc_registerErrorHandler(arg1);
}


SWIGEXPORT jint JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1getHashQueryStateToBuffer(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  result = (int)vc_getHashQueryStateToBuffer(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1Destroy(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  VC arg1 = (VC) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  vc_Destroy(arg1);
}


SWIGEXPORT void JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1DeleteExpr(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Expr arg1 = (Expr) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Expr *)&jarg1; 
  vc_DeleteExpr(arg1);
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1getWholeCounterExample(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  WholeCounterExample result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  result = (WholeCounterExample)vc_getWholeCounterExample(arg1);
  *(WholeCounterExample *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1getTermFromCounterExample(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  VC arg1 = (VC) 0 ;
  Expr arg2 = (Expr) 0 ;
  WholeCounterExample arg3 = (WholeCounterExample) 0 ;
  Expr result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = *(Expr *)&jarg2; 
  arg3 = *(WholeCounterExample *)&jarg3; 
  result = (Expr)vc_getTermFromCounterExample(arg1,arg2,arg3);
  *(Expr *)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1deleteWholeCounterExample(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  WholeCounterExample arg1 = (WholeCounterExample) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(WholeCounterExample *)&jarg1; 
  vc_deleteWholeCounterExample(arg1);
}


SWIGEXPORT jint JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_getExprKind(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  Expr arg1 = (Expr) 0 ;
  enum exprkind_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Expr *)&jarg1; 
  result = (enum exprkind_t)getExprKind(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_getDegree(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  Expr arg1 = (Expr) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Expr *)&jarg1; 
  result = (int)getDegree(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_getBVLength(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  Expr arg1 = (Expr) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Expr *)&jarg1; 
  result = (int)getBVLength(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_BOOLEAN_1TYPE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum type_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum type_t)BOOLEAN_TYPE;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_getType(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  Expr arg1 = (Expr) 0 ;
  enum type_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Expr *)&jarg1; 
  result = (enum type_t)getType(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_getVWidth(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  Expr arg1 = (Expr) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Expr *)&jarg1; 
  result = (int)getVWidth(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_getIWidth(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  Expr arg1 = (Expr) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Expr *)&jarg1; 
  result = (int)getIWidth(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1printCounterExampleFile(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  VC arg1 = (VC) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  arg2 = (int)jarg2; 
  vc_printCounterExampleFile(arg1,arg2);
}


SWIGEXPORT jstring JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_exprName(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jstring jresult = 0 ;
  Expr arg1 = (Expr) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Expr *)&jarg1; 
  result = (char *)exprName(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_getExprID(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  Expr arg1 = (Expr) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Expr *)&jarg1; 
  result = (int)getExprID(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1supportsMinisat(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jboolean jresult = 0 ;
  VC arg1 = (VC) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  result = (bool)vc_supportsMinisat(arg1);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1useMinisat(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jboolean jresult = 0 ;
  VC arg1 = (VC) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  result = (bool)vc_useMinisat(arg1);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1isUsingMinisat(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jboolean jresult = 0 ;
  VC arg1 = (VC) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  result = (bool)vc_isUsingMinisat(arg1);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1supportsSimplifyingMinisat(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jboolean jresult = 0 ;
  VC arg1 = (VC) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  result = (bool)vc_supportsSimplifyingMinisat(arg1);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1useSimplifyingMinisat(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jboolean jresult = 0 ;
  VC arg1 = (VC) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  result = (bool)vc_useSimplifyingMinisat(arg1);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1isUsingSimplifyingMinisat(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jboolean jresult = 0 ;
  VC arg1 = (VC) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  result = (bool)vc_isUsingSimplifyingMinisat(arg1);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1supportsCryptominisat(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jboolean jresult = 0 ;
  VC arg1 = (VC) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  result = (bool)vc_supportsCryptominisat(arg1);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1useCryptominisat(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jboolean jresult = 0 ;
  VC arg1 = (VC) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  result = (bool)vc_useCryptominisat(arg1);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1isUsingCryptominisat(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jboolean jresult = 0 ;
  VC arg1 = (VC) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  result = (bool)vc_isUsingCryptominisat(arg1);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1supportsRiss(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jboolean jresult = 0 ;
  VC arg1 = (VC) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  result = (bool)vc_supportsRiss(arg1);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1useRiss(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jboolean jresult = 0 ;
  VC arg1 = (VC) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  result = (bool)vc_useRiss(arg1);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_org_sosy_1lab_java_1smt_solvers_stp_StpJNI_vc_1isUsingRiss(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jboolean jresult = 0 ;
  VC arg1 = (VC) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(VC *)&jarg1; 
  result = (bool)vc_isUsingRiss(arg1);
  jresult = (jboolean)result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

